stages:
  - build
  # - test
  - deploy

variables:
  DOTNET_VERSION: "8.0"
  BUILD_CONFIG: "Release"
  PROJECT_PATH: "./LoreVault/LoreVault.API/LoreVault.API.csproj"
  IMAGE_NAME: "howtofail/lorevault-api"
  KUBE_NAMESPACE: "lorevault-testing"
  DEPLOYMENT_NAME: "lorevault-backend"

# Use .NET SDK image as the base image
image: mcr.microsoft.com/dotnet/sdk:8.0

# Add Docker service to enable Docker commands
services:
  - docker:24.0.5-dind

before_script:
  - apt-get update && apt-get install -y docker.io
  - echo "Using .NET version $DOTNET_VERSION"
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  # - export DOCKER_HOST=tcp://docker:2375

build:
  stage: build
  script:
    - docker build --build-arg BUILD_CONFIGURATION=$BUILD_CONFIG -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -f LoreVault/Dockerfile LoreVault/
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  # only:
  #   - development

# test:
#   stage: test
#   script:
#     - docker run --rm $IMAGE_NAME:$CI_COMMIT_SHORT_SHA dotnet test $PROJECT_PATH --no-build --verbosity normal
#   # only:
#   #   - development

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG" > /root/.kube/config
    # - kubectl -n $KUBE_NAMESPACE set image deployment/$DEPLOYMENT_NAME api=$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    # - kubectl -n $KUBE_NAMESPACE rollout status deployment/$DEPLOYMENT_NAME
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment/$DEPLOYMENT_NAME -n $KUBE_NAMESPACE
  only:
    - main
  when: manual