stages:
  - build
  - test
  - deploy

variables:
  DOTNET_VERSION: "8.0"
  BUILD_CONFIG: "Release"
  PROJECT_PATH: "./LoreVault/LoreVault.API/LoreVault.API.csproj"
  IMAGE_NAME: "registry.gitlab.com/I516586/lorevault/lorevault-api"

# Use .NET SDK image as the base image
image: mcr.microsoft.com/dotnet/sdk:8.0-alpine

# Add Docker service to enable Docker commands
services:
  - docker:20.10.16-dind

before_script:
  - echo "Using .NET version $DOTNET_VERSION"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build --build-arg BUILD_CONFIGURATION=$BUILD_CONFIG -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -f ./LoreVault/LoreVault.API/Dockerfile .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - development

test:
  stage: test
  script:
    - docker run --rm $IMAGE_NAME:$CI_COMMIT_SHORT_SHA dotnet test $PROJECT_PATH --no-build --verbosity normal
  only:
    - development

deploy:
  stage: deploy
  script:
    - echo "Deploying image $IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  only:
    - main
  when: manual