stages:
  - build
  - test
  - deploy

variables:
  DOTNET_VERSION: "8.0"
  BUILD_CONFIG: "Release"
  PROJECT_PATH: "./LoreVault/LoreVault.API/LoreVault.API.csproj"
  IMAGE_NAME: "howtofail/lorevault-api"
  KUBE_NAMESPACE: "lorevault-testing"
  DEPLOYMENT_NAME: "lorevault-backend"

# Use .NET SDK image as the base image
image: mcr.microsoft.com/dotnet/sdk:8.0

# Add Docker service to enable Docker commands
services:
  - docker:24.0.5-dind

before_script:
  - apt-get update && apt-get install -y docker.io
  - echo "Using .NET version $DOTNET_VERSION"
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  # - export DOCKER_HOST=tcp://docker:2375

build:
  stage: build
  script:
    - echo "Creating appsettings.json..."
    - echo "$APPSETTINGS" > LoreVault/LoreVault.API/appsettings.json
    - docker build --build-arg BUILD_CONFIGURATION=$BUILD_CONFIG -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest -f LoreVault/Dockerfile LoreVault/
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  # only:
  #   - development

test:
  stage: test
  script:
    - docker run --rm $IMAGE_NAME:$CI_COMMIT_SHORT_SHA dotnet test $PROJECT_PATH --no-build --verbosity normal
  # only:
  #   - development

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - export KUBECONFIG=$KUBECONFIG_FILE
  script:
    - apt-get update && apt-get install -y curl
    # Install kubectl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl apply -f deployment.yaml
    - kubectl set image deployment/$DEPLOYMENT_NAME api=$IMAGE_NAME:${CI_COMMIT_SHORT_SHA} -n $KUBE_NAMESPACE
    # Add an annotation to force a rollout
    - kubectl annotate deployment/$DEPLOYMENT_NAME kubernetes.io/change-cause="Redeploy at $(date)" --overwrite -n $KUBE_NAMESPACE
    - kubectl rollout status deployment/$DEPLOYMENT_NAME -n $KUBE_NAMESPACE
  only:
    - main
  when: manual